name: Run tests on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Report Test Results to GitHub
        uses: actions/github-script@v7
        with:
          script: |
            const { context, github } = require('@actions/github');

            const { data } = await github.checks.create({
              ...context.repo,
              name: 'Tests',
              head_sha: context.sha,
              status: 'completed',
              conclusion: '${{ job.status }}',
              output: {
                title: 'Test Results',
                summary: '${{ job.status }}'
              }
            });
